export const GmtList = [
  { zone: "미드웨이", time: "GMT -11:00" },
  { zone: "호놀룰루", time: "GMT -10:00" },
  { zone: "앵커리지", time: "GMT -09:00" },
  { zone: "태평양 표준시 (로스앤젤레스)", time: "GMT -08:00" },
  { zone: "태평양 표준시 (티후아나)", time: "GMT -08:00" },
  { zone: "산지 표준시 (피닉스)", time: "GMT -07:00" },
  { zone: "치와와", time: "GMT -07:00" },
  { zone: "산지 표준시 (덴버)", time: "GMT -07:00" },
  { zone: "중부 표준시 (코스타리카)", time: "GMT -06:00" },
  { zone: "중부 표준시 (시카고)", time: "GMT -06:00" },
  { zone: "중부 표준시 (멕시코 시티)", time: "GMT -06:00" },
  { zone: "중부 표준시 (리자이나)", time: "GMT -06:00" },
  { zone: "보고타", time: "GMT -05:00" },
  { zone: "동부 표준시 (뉴욕)", time: "GMT -05:00" },
  { zone: "카라카스", time: "GMT -04:30" },
  { zone: "대서양 표준시 (바베이도스)", time: "GMT -04:00" },
  { zone: "아마존 표준시 (마나우스)", time: "GMT -04:00" },
  { zone: "뉴펀들랜드 표준시 (세인트존)", time: "GMT -03:00" },
  { zone: "산티아고", time: "GMT -03:00" },
  { zone: "브라질리아 표준시 (상파올로)", time: "GMT -03:00" },
  { zone: "부에노스 아이레스", time: "GMT -03:00" },
  { zone: "고드호프", time: "GMT -03:00" },
  { zone: "몬테비데오", time: "GMT -02:00" },
  { zone: "사우스 조지아 표준시 (남부 조지아)", time: "GMT -02:00" },
  { zone: "아조레스", time: "GMT -01:00" },
  { zone: "카보 베르데 표준시 (카보베르데)", time: "GMT -01:00" },
  { zone: "카사블랑카", time: "GMT +00:00" },
  { zone: "그리니치 표준시 (런던)", time: "GMT +00:00" },
  { zone: "중부유럽 표준시 (암스테르담)", time: "GMT +01:00" },
  { zone: "중부유럽 표준시 (Belgrade)", time: "GMT +01:00" },
  { zone: "중부유럽 표준시 (브뤼셀)", time: "GMT +01:00" },
  { zone: "중부유럽 표준시 (Sarajevo)", time: "GMT +01:00" },
  { zone: "서아프리카 시간 (브라자빌)", time: "GMT +01:00" },
  { zone: "빈트후크", time: "GMT +02:00" },
  { zone: "동부유럽 표준시 (암만)", time: "GMT +02:00" },
  { zone: "동부유럽 표준시 (아테네)", time: "GMT +02:00" },
  { zone: "동부유럽 표준시 (베이루트)", time: "GMT +02:00" },
  { zone: "동부유럽 표준시 (카이로)", time: "GMT +02:00" },
  { zone: "동부유럽 표준시 (헬싱키)", time: "GMT +02:00" },
  { zone: "이스라엘 표준시 (예루살렘)", time: "GMT +02:00" },
  { zone: "민스크", time: "GMT +02:00" },
  { zone: "중앙아프리카 시간 (하라레)", time: "GMT +02:00" },
  { zone: "아라비아 시간 (바그다드)", time: "GMT +03:00" },
  { zone: "모스크바", time: "GMT +03:00" },
  { zone: "아라비아 시간 (쿠웨이트)", time: "GMT +03:00" },
  { zone: "동아프리카 시간 (나이로비)", time: "GMT +03:00" },
  { zone: "테헤란", time: "GMT +03:30" },
  { zone: "바쿠", time: "GMT +04:00" },
  { zone: "트빌리시", time: "GMT +04:00" },
  { zone: "예레반", time: "GMT +04:00" },
  { zone: "두바이", time: "GMT +04:00" },
  { zone: "카불", time: "GMT +04:30" },
  { zone: "카라치", time: "GMT +05:00" },
  { zone: "오랄", time: "GMT +05:00" },
  { zone: "예카테린부르크", time: "GMT +05:00" },
  { zone: "인도 표준시 (Calcutta)", time: "GMT +05:30" },
  { zone: "콜롬보", time: "GMT +05:30" },
  { zone: "카트만두", time: "GMT +05:45" },
  { zone: "알마티", time: "GMT +06:00" },
  { zone: "랑군", time: "GMT +06:30" },
  { zone: "크라스노야르스크", time: "GMT +07:00" },
  { zone: "방콕", time: "GMT +07:00" },
  { zone: "중국 표준시 (베이징)", time: "GMT +08:00" },
  { zone: "홍콩", time: "GMT +08:00" },
  { zone: "이르쿠츠크", time: "GMT +08:00" },
  { zone: "쿠알라룸푸르", time: "GMT +08:00" },
  { zone: "서부 오스트레일리아 시간 (퍼스)", time: "GMT +08:00" },
  { zone: "타이베이", time: "GMT +08:00" },
  { zone: "한국 표준시 (서울)", time: "GMT +09:00" },
  { zone: "일본 표준시 (도쿄)", time: "GMT +09:00" },
  { zone: "야쿠츠크", time: "GMT +09:00" },
  { zone: "중앙 오스트레일리아 시간 (다윈)", time: "GMT +09:30" },
  { zone: "동부 오스트레일리아 시간 (브리스베인)", time: "GMT + 10:00" },
  { zone: "블라디보스토크", time: "GMT + 10:00" },
  { zone: "괌", time: "GMT + 10:00" },
  { zone: "중앙 오스트레일리아 시간 (애들레이드)", time: "GMT + 10:30" },
  { zone: "동부 오스트레일리아 시간 (호바트)", time: "GMT + 11:00" },
  { zone: "동부 오스트레일리아 시간 (시드니)", time: "GMT + 11:00" },
  { zone: "마가단", time: "GMT + 11:00" },
  { zone: "마주로", time: "GMT + 12:00" },
  { zone: "피지 표준시 (피지)", time: "GMT + 12:00" },
  { zone: "뉴질랜드 시간 (오클랜드)", time: "GMT + 13:00" },
  { zone: "통가타푸", time: "GMT + 13:00" },
];
